### ISSUE TITLE
When section has multiple preview targets, plugin settings overlay target selector

### ISSUE THREAD

**Issue by jwrudzin** [michaelhue/craft-breakpoint#4] opened 2020-09-23 01:11 UTC
## Description

When a section has multiple preview targets, the breakpoint plugin settings overlay the preview target selector and the selector can't be accessed.

<img width="1289" alt="Screen Shot 2020-09-22 at 9 09 33 PM" src="https://user-images.githubusercontent.com/18213990/93952954-20d39100-fd18-11ea-9e52-21ff731f3580.png">
<img width="1290" alt="Screen Shot 2020-09-22 at 9 08 43 PM" src="https://user-images.githubusercontent.com/18213990/93952955-216c2780-fd18-11ea-8459-b5121e5bf9b6.png">

## To Reproduce

1. Install breakpoint plugin.
2. Set up multiple preview targets for a section.
3. Open live preview for that section and trigger breakpoint plugin.

## Expected behavior

Plugin styles should adjust to move breakpoint settings out of the way of the preview target selector.

## Additional context

- Plugin version: 2.2.1
- Craft version: 3.4.24
- Browser and version: Chrome 85.0.4183.121

**Comment by michaelhue** [comment] 2020-09-24 13:07
Hey, thanks for the report!
I believe this is a duplicate of issue #2.

This is a problem with Craft 3.4, check [this issue](https://github.com/craftcms/cms/issues/5547) over on the Craft repo. It has been fixed in 3.5.

Would it be possible to update your project to the latest Craft version?

**Comment by jwrudzin** [comment] 2020-09-24 13:44
Hi @michaelhue!

Unfortunately, I'm still seeing this issue in Craft 3.5.10.1. It appears that Craft issue (#5547) refers to the live preview content being hidden underneath the header, but doesn't reference the issue with the content inside the header.

**Comment by michaelhue** [comment] 2020-09-24 14:43
Thanks for checking. I'll look into it!

**Comment by jwrudzin** [comment] 2020-10-13 00:58
Hi @michaelhue just checking to see if you've had a chance to look into this yet? Thanks!

**Closed as completed** 2020-10-13 08:10 UTC
Labels: bug

**Comment by michaelhue** [comment] 2020-10-13 08:14
Hey @jwrudzin, the issue should be fixed now. Please update to version `2.2.2`.

Thanks for your patience!
